name: 处理请求

on:
  issues:
    types: [opened]

jobs:
  process-issue:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Run issue-handle.py
        run: python scripts/issue-handle.py "${{ github.event.issue.title }}" "${{ github.event.issue.user.login }}"

      - name: Check script exit status
        run: |
          if [ $? -ne 0 ]; then
            echo "Python script failed, exiting..."
            exit 1
          fi

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git reset message.txt
          MESSAGE=$(cat message.txt)
          git commit -m "$MESSAGE"
          git push origin game
